### ISSUE TITLE
Loading model problems

### ISSUE THREAD

**Issue by Curlyhub** [philipperemy/keras-attention-mechanism#53]
When I'm trying to load a saved model, I get the following error. ! "A `Dot` layer should be called on a list of 2 inputs".

**Comment by DyeKuu** [comment]
I've met the same problem.

`Traceback (most recent call last):
  File "/home/cedar/kzheng/MAP569_AMF_Challenge/resume_training.py", line 97, in <module>
    model = keras.models.load_model(MODEL_PATH)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 177, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 171, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 488, in from_config
    model.add(layer)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 221, in add
    output_tensor = layer(self.outputs[0])
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/cedar/kzheng/anaconda3/envs/gt/lib/python3.8/site-packages/tensorflow/python/keras/layers/merge.py", line 663, in build
    raise ValueError('A `Dot` layer should be called '`

**Comment by philipperemy** [comment]
Yes use the functional API and it will work. There are some problems with Sequential.

**Comment by philipperemy** [comment]
```python
model_input = Input(shape=(seq_length, 1))
x = LSTM(100, input_shape=(seq_length, 1), return_sequences=True)(model_input)
x = Attention(name='attention_weight')(x)
x = Dropout(0.2)(x)
x = Dense(1, activation='linear')(x)
model = Model(model_input, x)
model.compile(loss='mse', optimizer='adam')
```

```python
# test save/reload model.
pred1 = model.predict(x_val)
model.save('test_model.h5')
model_h5 = load_model('test_model.h5')
pred2 = model_h5.predict(x_val)
np.testing.assert_almost_equal(pred1, pred2)
```

**Comment by philipperemy** [comment]
I'll close this issue for now. Thank you guys for your help!
